---
- name: Manage SmartGridMockApp
  hosts: all
  gather_facts: no
  vars:
    app_dir: /home/dlyog/ted/omniagent/SmartGridMockApp
    app_action: ""
  tasks:
    - name: Check if the application is running
      shell: "ps -ef | grep '[p]ython {{ app_dir }}/app.py'"
      ignore_errors: yes
      register: app_status

    - name: Set application running fact
      set_fact:
        app_running: "{{ app_status.rc == 0 }}"

    - name: Stop the application if it is running and app_action is stop
      when: app_action == "stop" and app_running
      command: "{{ app_dir }}/stop.sh"
      register: stop_output

    - name: Stop the application if it is running and app_action is start
      when: app_action == "start" and app_running
      command: "{{ app_dir }}/stop.sh"
      register: stop_output

    - name: Start the application if app_action is start
      when: app_action == "start"
      command: "{{ app_dir }}/start.sh"
      register: start_output

    - name: Display stop output
      when: (app_action == "stop" and app_running) or (app_action == "start" and app_running)
      debug:
        msg: "{{ stop_output.stdout | default('No stop output') }}"

    - name: Display start output
      when: app_action == "start"
      debug:
        msg: "{{ start_output.stdout | default('No start output') }}"
