---
- name: Test connectivity and gather OS info
  hosts: all
  tasks:
    - name: Gather OS info
      ansible.builtin.setup:
        gather_subset:
          - "hardware"
          - "network"
          - "virtual"
          - "facter"
          - "ohai"
